# Cloudflare Pages configuration for @nala/showcase
# https://developers.cloudflare.com/pages/configuration/wrangler-configuration/

name = "nala"
pages_build_output_dir = "./dist"
compatibility_date = "2026-08-27"
